[package]
name = "surrealdb-migrate"
version = "0.1.0"
edition = "2021"
authors = ["haraldmaida"]
license = "MIT/Apache-2.0"

description = """
Evolve a SurrealDB database over time by applying migrations. `surrealdb-migrate` is a commandline
tool and lib to define and run migrations on the database. It provides version control for a
[SurrealDB] database in a project.
"""
keywords = ["database", "migrations", "version-control", "cli2"]

[features]
proptest-support = ["dep:proptest"]

[dependencies]
crc32fast = "1"
thiserror = "2"
time = { version = "0.3", features = ["macros", "formatting", "parsing"] }

# optional
proptest = { version = "1", optional = true }

[dev-dependencies]
proptest = "1"
speculoos = "0.11"

[lints.rust]
unsafe_code = "forbid"
unstable_features = "forbid"
bare_trait_objects = "warn"
deprecated = "warn"
explicit_outlives_requirements = "warn"
noop_method_call = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
rust_2021_incompatible_closure_captures = "warn"
rust_2021_incompatible_or_patterns = "warn"
rust_2021_prefixes_incompatible_syntax = "warn"
rust_2021_prelude_collisions = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused_crate_dependencies = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
#variant_size_differences = "warn"  # enable when working on performance
#missing_docs = "warn"  # uncomment when working on docs
dead_code = "allow"  # remove eventually

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
enum_glob_use = "deny"
future_not_send = "allow"
missing_const_for_fn = "warn"
module_name_repetitions = "allow"
must_use_candidate = "allow"
unwrap_used = "deny"
missing_errors_doc = "allow"  # remove when working on docs
missing_panics_doc = "allow"  # remove when working on docs

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.proptest]
overflow-checks = false
